apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.model.name }}-ingress
  namespace: {{ .Values.model.name }}
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    #nginx.ingress.kubernetes.io/rewrite-target: /$2
    #kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ .Values.model.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.model.name }}-service
                port:
                  number: {{ .Values.model.port }}
