model:
  name: fueled-backend-dev
  profile: dev
  imageRepoUrl: 328342853006.dkr.ecr.us-east-1.amazonaws.com
  imageRepoName: fueld-backend-dev
  imageTag: latest
  replica: 1
  maxSurge: 1
  maxUnavailable: 1
  minReadySeconds: 30
  port: 3000
  imagePullSecrets: aws-ecr
  env:
    imagePullPolicy: IfNotPresent